### ISSUE TITLE
poica

### ISSUE THREAD

**Issue by Hirrolot** [oz123/awesome-c#145]
I've published a new library for algebraic data types - [poica](https://github.com/Hirrolot/poica).

1) Do you think it deserves to be on your list?
2) If so, to which category in `README.md` does it correspond?

**Comment by kozross** [comment]
This seems to have a close reliance on Boost, which is C++. Since this is for pure C, that would put it out of scope. Please let me know if I'm missing something?

**Comment by Hirrolot** [comment]
Boost/Preprocessor actually [supports C/C++](https://www.boost.org/doc/libs/1_53_0/libs/preprocessor/doc/). It compiles fine with `gcc -std=c11`.

**Comment by Hirrolot** [comment]
The project is abandoned.
