### ISSUE TITLE
Retiring from maintaining this list

### ISSUE THREAD

**Issue by kozross** [oz123/awesome-c#164]
OK, so, it's been a while, but I'm increasingly finding myself unable to give this list the love and attention it deserves. I'm happy that many folks have found it useful, and also that many of you put up with my (increasingly irregular) maintenance of it while trying to contribute. It's been good and fun, but my life's moved on.

I'm happy to pass maintenance of this list over to someone else, along with its (somewhat stale) mirror on NotABug if you want it. Let me know, and we'll work something out. I'll keep up maintenance (or as much as I've managed of it) for now, but I'm definitely looking to hand it over to someone who can give it the attention and care it deserves.

**Comment by oz123** [comment]
I'd like to give it a shot.

**Comment by kozross** [comment]
@oz123 Thank you! I've put through the transfer of this repo to you. Let me know if you want the NAB one as well - otherwise, best of luck, and happy maintenance!
