### ISSUE TITLE
exengine

### ISSUE THREAD

**Issue by MatheusKS95** [oz123/awesome-c#236]
https://github.com/solenum/exengine

I think exengine could be included. It's a 3D game engine/game template written in C99 made by solenum, licensed under MIT. Works with Linux, Windows and OpenBSD.

Note: it's not my project however, I came across it and I'm playing with it.

**Comment by oz123** [comment]
Nice! Can you please send a PR?

**Comment by MatheusKS95** [comment]
Opened PR #237
