### ISSUE TITLE
add SDK

### ISSUE THREAD

**Issue by diamant3** [oz123/awesome-c#250]
When it comes to SDK, where do I need to put this to add this to the list? or maybe create a new list for SDK? This is the [organization](https://github.com/pspdev/pspdev) i want to add, It's SDK for creating homebrew apps/games for PSP, thanks.

**Comment by oz123** [comment]
Please create a PR only with https://github.com/pspdev/pspsdk. I will merge. 
Thanks.

**Comment by diamant3** [comment]
I got it. thanks!

**Comment by oz123** [comment]
Frameworks, ofcourse :-)

**Comment by diamant3** [comment]
Okay, thank you!

**Comment by diamant3** [comment]
Thank you! i will close this now.
