### ISSUE TITLE
blend2d

### ISSUE THREAD

**Issue by myd7349** [oz123/awesome-c#96]
https://github.com/blend2d/blend2d

**Comment by Bfgeshka** [comment]
This is C++ project.

**Comment by myd7349** [comment]
>Blend2D is written in C++ but it provides both C and C++ APIs.

**Comment by kozross** [comment]
Sorry for the delay @myd7349 - I'm _definitely_ torn about this one. While CONTRIBUTING.md technically doesn't prohibit this from being included, I'm curious just how likely it is that C++ knowledge or understanding would need to creep in when using the C API. For example: Suppose I write something daft and have to debug. Do I need to know C++ to debug use of this library from C successfully?

**Comment by myd7349** [comment]
Hi! @kozross Some knowledge about C++ is necessary if the users want to debug the source code. We do not have to be a C++ expert, however. Besides, this library doesn't use too much advanced C++ features at first glance.
AFAIK, C++ is not the hardest part when hacking this library, especially compared to those professional graphics & JIT compiler knowledge the users may have to learn if they want to totally understand the source code.
Some other libraries, like `ZeroMQ`, also implemented with C++, and provides C APIs. If C++ is not a problem for `ZeroMQ` users, then I think it should not be a problem for `blend2d` users either.
Anyway, I think C programmers may benefit from this library.

**Comment by kozross** [comment]
@myd7349 Thanks for getting back to me. Sorry if I wasn't clear - my specific question was this: suppose I, a C programmer who knows nothing of C++, want to use `blend2d`'s C API. In the process of doing that, I write something that requires use of the debugger to fix. As a C programmer, would I find it difficult to do this, knowing no C++ at all? Or are the bindings fairly 'opaque' to the fact that `blend2d` itself is implemented in C++?
